"""empty message

Revision ID: 035d15fae75f
Revises: 02a93e16589f
Create Date: 2021-11-01 14:26:15.865882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035d15fae75f'
down_revision = '02a93e16589f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
