"""empty message

Revision ID: 03feb7394905
Revises: 4acd228110a2
Create Date: 2021-11-01 16:16:17.068697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03feb7394905'
down_revision = '4acd228110a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('description', sa.String(), nullable=True))
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    op.drop_column('goal', 'description')
    # ### end Alembic commands ###
