"""empty message

Revision ID: 08865ae3f185
Revises: 4cd9ff1585d1
Create Date: 2021-10-29 13:59:06.344473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08865ae3f185'
down_revision = '4cd9ff1585d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
