"""empty message

Revision ID: 0bae5e9fe5ca
Revises: acae80863782
Create Date: 2021-10-31 14:24:45.399927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bae5e9fe5ca'
down_revision = 'acae80863782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('fk_goal_id', sa.Integer(), nullable=True))
    op.drop_constraint('tasks_goal_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'goals', ['fk_goal_id'], ['goal_id'])
    op.drop_column('tasks', 'goal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('goal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_goal_id_fkey', 'tasks', 'goals', ['goal_id'], ['goal_id'])
    op.drop_column('tasks', 'fk_goal_id')
    # ### end Alembic commands ###
