"""adds Goal model

Revision ID: 11db0075866d
Revises: ad18144173ca
Create Date: 2021-11-01 15:53:48.713124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11db0075866d'
down_revision = 'ad18144173ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=False))
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
