"""empty message

Revision ID: 123332d46b03
Revises: 5874a9a93bb7
Create Date: 2021-10-27 13:57:30.010802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123332d46b03'
down_revision = '5874a9a93bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.drop_table('task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('task_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('task_id', name='task_pkey')
    )
    op.drop_table('tasks')
    # ### end Alembic commands ###
