"""empty message

Revision ID: 1447430f54a7
Revises: 5aaab56a6e4c
Create Date: 2021-11-01 12:06:23.239450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1447430f54a7'
down_revision = '5aaab56a6e4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('goal_task_id_fkey', 'goal', type_='foreignkey')
    op.drop_column('goal', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('goal_task_id_fkey', 'goal', 'task', ['task_id'], ['task_id'])
    # ### end Alembic commands ###
