"""empty message

Revision ID: 163195003254
Revises: fa44f3492fa7
Create Date: 2021-10-28 08:47:45.741996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163195003254'
down_revision = 'fa44f3492fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'is_complete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'is_complete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
