"""empty message

Revision ID: 2a027b9eb6f5
Revises: 567b4d99c64e
Create Date: 2021-11-03 21:27:41.145478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a027b9eb6f5'
down_revision = '567b4d99c64e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('id', sa.Integer(), autoincrement=True, nullable=True))
    op.drop_column('task', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_id', sa.INTEGER(), autoincrement=True, nullable=True))
    op.drop_column('task', 'id')
    # ### end Alembic commands ###
