"""empty message

Revision ID: 390c60aee6a1
Revises: 5ec289939f0b
Create Date: 2021-11-04 10:41:41.983889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390c60aee6a1'
down_revision = '5ec289939f0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.drop_constraint('task_one_goal_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    op.drop_column('task', 'one_goal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('one_goal', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_one_goal_fkey', 'task', 'goal', ['one_goal'], ['goal_id'])
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
