"""Adds to_dict method within Tasks Model and configures routes to database setup

Revision ID: 42a3f3d5180b
Revises: f287a0dde60d
Create Date: 2021-10-29 10:42:08.065803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42a3f3d5180b'
down_revision = 'f287a0dde60d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('description', sa.String(), nullable=True))
    op.add_column('task', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('task', 'task_completed_at')
    op.drop_column('task', 'task_description')
    op.drop_column('task', 'task_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('task_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('task_completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('task', 'title')
    op.drop_column('task', 'description')
    op.drop_column('task', 'completed_at')
    # ### end Alembic commands ###
