"""empty message

Revision ID: 4817fc04d97e
Revises: 481b7755ccc3
Create Date: 2021-11-03 19:35:47.589900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4817fc04d97e'
down_revision = '481b7755ccc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###
