"""empty message

Revision ID: 496a7c526927
Revises: a40d294d7311
Create Date: 2021-10-30 15:09:03.524053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496a7c526927'
down_revision = 'a40d294d7311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
