"""empty message

Revision ID: 4acd228110a2
Revises: e378c4a27f72
Create Date: 2021-10-27 17:59:58.337620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4acd228110a2'
down_revision = 'e378c4a27f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('task', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('task', 'title')
    op.drop_column('task', 'completed_at')
    # ### end Alembic commands ###
