"""add new attribute to goal class

Revision ID: 51e276c7d088
Revises: 63cdb5b5fc6a
Create Date: 2021-11-01 14:44:59.323655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e276c7d088'
down_revision = '63cdb5b5fc6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
