"""empty message

Revision ID: 5aaab56a6e4c
Revises: c4cafa2d950f
Create Date: 2021-11-01 10:54:46.539990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aaab56a6e4c'
down_revision = 'c4cafa2d950f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'goal', 'task', ['task_id'], ['task_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goal', type_='foreignkey')
    op.drop_column('goal', 'task_id')
    # ### end Alembic commands ###
