"""empty message

Revision ID: 5ec289939f0b
Revises: e50e5030ef79
Create Date: 2021-11-04 10:15:34.180205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec289939f0b'
down_revision = 'e50e5030ef79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('one_goal', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['one_goal'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'one_goal')
    # ### end Alembic commands ###
