"""empty message

Revision ID: 61b24becabea
Revises: 331a96b67fcf
Create Date: 2021-11-03 16:14:42.615009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b24becabea'
down_revision = '331a96b67fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.drop_constraint('tasks_goal_id_a_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'goals', ['goal_id'], ['goal_id'])
    op.drop_column('tasks', 'goal_id_a')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('goal_id_a', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_goal_id_a_fkey', 'tasks', 'goals', ['goal_id_a'], ['goal_id'])
    op.drop_column('tasks', 'goal_id')
    # ### end Alembic commands ###
