"""empty message

Revision ID: 658c883b5a8e
Revises: 7977ed269029
Create Date: 2021-10-31 10:46:26.295529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658c883b5a8e'
down_revision = '7977ed269029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
