"""empty message

Revision ID: 675fb5c1f7cf
Revises: 0e63a250cd06
Create Date: 2021-11-03 11:38:14.143218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675fb5c1f7cf'
down_revision = '0e63a250cd06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'title')
    # ### end Alembic commands ###
