"""empty message

Revision ID: 68024bf8361c
Revises: 9d1b3e3e4073
Create Date: 2021-10-27 16:22:33.780980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68024bf8361c'
down_revision = '9d1b3e3e4073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###
