"""empty message

Revision ID: 6f7e7b2f7d0f
Revises: c7bbf8f17bcc
Create Date: 2021-11-04 11:33:51.999832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f7e7b2f7d0f'
down_revision = 'c7bbf8f17bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.drop_table('goal')
    op.drop_constraint('tasks_goal_id_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'goal_id')
    op.drop_column('tasks', 'is_complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('goal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tasks_goal_id_fkey', 'tasks', 'goal', ['goal_id'], ['goal_id'])
    op.create_table('goal',
    sa.Column('goal_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('goal_id', name='goal_pkey')
    )
    op.drop_table('goals')
    # ### end Alembic commands ###
