"""empty message

Revision ID: 84116e12726b
Revises: e0d349db82f9
Create Date: 2021-11-02 16:25:08.822830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84116e12726b'
down_revision = 'e0d349db82f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
