"""empty message

Revision ID: 844a39139754
Revises: 07e1d8c411bc
Create Date: 2021-10-27 16:51:03.498730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844a39139754'
down_revision = '07e1d8c411bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('is_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    op.drop_column('task', 'completed_at')
    # ### end Alembic commands ###
