"""empty message

Revision ID: 90adfddb91b1
Revises: 9dc4a214948b
Create Date: 2021-11-01 21:35:19.345015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90adfddb91b1'
down_revision = '9dc4a214948b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
