"""empty message

Revision ID: 950b5cdd5a2a
Revises: 001991e91f43
Create Date: 2021-11-04 15:04:03.443481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950b5cdd5a2a'
down_revision = '001991e91f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
