"""creates goal model and registers with the __init__ file

Revision ID: 963b02e868cb
Revises: 42a3f3d5180b
Create Date: 2021-11-01 20:41:05.364207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963b02e868cb'
down_revision = '42a3f3d5180b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
