"""empty message

Revision ID: 995547d5ad1c
Revises: cabb60e47e6c
Create Date: 2021-10-29 18:06:12.606814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995547d5ad1c'
down_revision = 'cabb60e47e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
