"""updates nullable constraint for title and description attributes

Revision ID: 995e2b059e0a
Revises: b1980e0a8b51
Create Date: 2021-11-01 22:09:36.638916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995e2b059e0a'
down_revision = 'b1980e0a8b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
