"""set one-to-many relationship

Revision ID: a6b05761ac7e
Revises: 7cc5c075367b
Create Date: 2021-11-04 00:10:43.988677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b05761ac7e'
down_revision = '7cc5c075367b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('goal_id_fk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'goals', ['goal_id_fk'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'goal_id_fk')
    # ### end Alembic commands ###
