"""Formed foreign key and one-to-many-relationship

Revision ID: acae80863782
Revises: 2d017be8dec8
Create Date: 2021-10-31 13:49:23.976501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acae80863782'
down_revision = '2d017be8dec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'goals', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'goal_id')
    # ### end Alembic commands ###
