"""changed name attribute to title attribute

Revision ID: b470e7aaab8e
Revises: ba46f6abb613
Create Date: 2021-10-29 09:41:29.519791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b470e7aaab8e'
down_revision = 'ba46f6abb613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('task', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('task', 'title')
    # ### end Alembic commands ###
