"""task can have nullable goal_id

Revision ID: b97492434a08
Revises: 9ca296f3d9e4
Create Date: 2021-11-01 20:20:29.292488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b97492434a08'
down_revision = '9ca296f3d9e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'goal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'goal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
