"""empty message

Revision ID: c7bbf8f17bcc
Revises: 9d6cc257f817
Create Date: 2021-11-04 09:18:59.379591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7bbf8f17bcc'
down_revision = '9d6cc257f817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('is_complete', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'is_complete')
    op.drop_column('tasks', 'goal_id')
    # ### end Alembic commands ###
