"""empty message

Revision ID: cc11d2cd3268
Revises: 21387c63824d
Create Date: 2021-11-01 18:02:41.274447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc11d2cd3268'
down_revision = '21387c63824d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
