"""empty message

Revision ID: cf4dd380d020
Revises: d68422dfb9d2
Create Date: 2021-10-31 14:06:51.372159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf4dd380d020'
down_revision = 'd68422dfb9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'goal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'goal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
