"""empty message

Revision ID: d06d4324086a
Revises: d08d2324bdea
Create Date: 2021-11-02 16:35:01.482006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06d4324086a'
down_revision = 'd08d2324bdea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'goal', 'task', ['task_id'], ['task_id'])
    op.drop_constraint('task_goal_id_fkey', 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('task_goal_id_fkey', 'task', 'goal', ['goal_id'], ['goal_id'])
    op.drop_constraint(None, 'goal', type_='foreignkey')
    op.drop_column('goal', 'task_id')
    # ### end Alembic commands ###
