"""empty message

Revision ID: d68422dfb9d2
Revises: 457dea5c580e
Create Date: 2021-10-30 17:48:19.354654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68422dfb9d2'
down_revision = '457dea5c580e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'goal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'goal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
