"""empty message

Revision ID: da7746a2df8f
Revises: 85537e5e6260
Create Date: 2021-11-03 21:05:39.583977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da7746a2df8f'
down_revision = '85537e5e6260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('title', sa.String(length=200), nullable=True))
    op.drop_column('goals', 'goal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('goal', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('goals', 'title')
    # ### end Alembic commands ###
