"""empty message

Revision ID: fef0e628d535
Revises: 8bc1a24afd84
Create Date: 2021-11-04 00:38:40.104773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef0e628d535'
down_revision = '8bc1a24afd84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('task', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('task', 'task_id')
    # ### end Alembic commands ###
