"""empty message

Revision ID: 4a065e3df323
Revises: fb31a6d48b69
Create Date: 2021-11-07 16:00:58.935816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a065e3df323'
down_revision = 'fb31a6d48b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('goal', 'identification')
    op.add_column('task', sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('task', 'identification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('identification', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('task', 'task_id')
    op.add_column('goal', sa.Column('identification', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('goal', 'goal_id')
    # ### end Alembic commands ###
