"""empty message

Revision ID: fb31a6d48b69
Revises: 3fba307a87ce
Create Date: 2021-11-04 12:09:28.045500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb31a6d48b69'
down_revision = '3fba307a87ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('identification', sa.Integer(), nullable=False))
    op.add_column('goal', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('goal', 'goal_id')
    op.add_column('task', sa.Column('identification', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('task', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('task', 'identification')
    op.add_column('goal', sa.Column('goal_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('goal', 'title')
    op.drop_column('goal', 'identification')
    # ### end Alembic commands ###
